on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        path: main
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v8
      with:
        dry_run: false
        
# Setup by Ian 2023-03-09
# See: https://github.com/getnikola/nikola-action
# was: actions/checkout@v3
# was: getnikola/nikola-action@v4    
# Add with:
#    path: main
